# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v1
          with:
            node-version: 10.x
        - run: npm install
        - run: npm run build --if-present
        - run: echo "::set-env m8_version=node get-version.js"
        
      - name: test
        - run: echo $m8_version
#      - name: Commit
#        - run: echo $m8_version
#      - name: Push
#        uses: ad-m/github-push-action@v0.6.0
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
